/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAutoComplete: typeof import('ant-design-vue/es')['AutoComplete']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ARate: typeof import('ant-design-vue/es')['Rate']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AuthCard: typeof import('./src/components/Auth/AuthCard.vue')['default']
    AutoComplete: typeof import('./src/components/AutoComplete.vue')['default']
    Checkbox: typeof import('./src/components/Form/Checkbox.vue')['default']
    CustomInput: typeof import('./src/components/Form/CustomInput.vue')['default']
    DatePicker: typeof import('./src/components/Form/DatePicker.vue')['default']
    HeaderCategories: typeof import('./src/components/Header/HeaderCategories.vue')['default']
    ItemCard: typeof import('./src/components/ItemCard.vue')['default']
    LoginCard: typeof import('./src/components/Auth/LoginCard.vue')['default']
    MainHeader: typeof import('./src/components/Header/MainHeader.vue')['default']
    RegisterCard: typeof import('./src/components/Auth/RegisterCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/Slider.vue')['default']
  }
}
